#!/usr/bin/expect
set timeout 30
set host [lindex $argv 0]
set username [lindex $argv 1]
set password [lindex $argv 2]
set src_file [lindex $argv 3]
set dest_file [lindex $argv 4]

spawn scp -r $username@$host:$src_file $dest_file
expect {
  "*assword" {set timeout 300; send "$password\n";}
  "yes/no" {send "yes\n"}
}
expect eof
